/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

/**
 *
 * @author Fiore
 */
public class VistaMenuOpciones extends javax.swing.JFrame {

    /**
     * Creates new form VistaMenuOpciones
     */
    public VistaMenuOpciones() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonIntegrantes = new javax.swing.JButton();
        jButtonOperaiones = new javax.swing.JButton();
        jLabelUpao = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabelFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonIntegrantes.setBackground(new java.awt.Color(0, 0, 51));
        jButtonIntegrantes.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jButtonIntegrantes.setForeground(new java.awt.Color(255, 255, 255));
        jButtonIntegrantes.setText("Integrantes");
        jButtonIntegrantes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonIntegrantesActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonIntegrantes, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 210, 170, 50));

        jButtonOperaiones.setBackground(new java.awt.Color(0, 0, 51));
        jButtonOperaiones.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jButtonOperaiones.setForeground(new java.awt.Color(255, 255, 255));
        jButtonOperaiones.setText("Operaciones con Matrices");
        jButtonOperaiones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOperaionesActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonOperaiones, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 330, 310, 50));

        jLabelUpao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/logoUpao.png"))); // NOI18N
        getContentPane().add(jLabelUpao, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 120));

        jButton1.setBackground(new java.awt.Color(0, 0, 51));
        jButton1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Cerrar Sesión");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 440, 180, 40));

        jLabelFondo.setForeground(new java.awt.Color(255, 255, 255));
        jLabelFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/hd_wallpaper_blue_017.jpg"))); // NOI18N
        getContentPane().add(jLabelFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonIntegrantesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonIntegrantesActionPerformed
            VistaAcercaDe va=new VistaAcercaDe();
            va.setVisible(true);
            dispose();        
    }//GEN-LAST:event_jButtonIntegrantesActionPerformed

    private void jButtonOperaionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOperaionesActionPerformed
        VistaMatrizIngresando vm=new VistaMatrizIngresando();
        vm.setVisible(true);
        dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonOperaionesActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        System.exit(0);  //para salir        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaMenuOpciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaMenuOpciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaMenuOpciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaMenuOpciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaMenuOpciones().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonIntegrantes;
    private javax.swing.JButton jButtonOperaiones;
    private javax.swing.JLabel jLabelFondo;
    private javax.swing.JLabel jLabelUpao;
    // End of variables declaration//GEN-END:variables
}
